import type { Metadata } from "next";
import {
  Geist,
  Inter,
  Plus_Jakarta_Sans,
  Libre_Baskerville,
} from "next/font/google";
import { ReactLenis } from "@/utils/lenis";
import "./globals.css";
import Overlay from "@/components/Overlay";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const libre = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: ["700"],
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${inter.variable} ${jakarta.variable} ${libre.variable}`}
    >
      <body className="antialiased">
        <ReactLenis root>
          <Overlay />
          <div className="relative z-10">{children}</div>
          <Toaster />
        </ReactLenis>
      </body>
    </html>
  );
}
